### ISSUE TITLE
Getting all possible routes

### ISSUE THREAD

**Issue by rishav-karanjit** [Esri/esri-leaflet-routing#18]
Is it possible to get all possible routes between two coordinates (or at least 5+ routes)?

**Comment by gavinr** [comment]
Hi, since this repo has not been maintained in awhile, I'd suggest you look at the ArcGIS REST Routing endpoints:

- https://developers.arcgis.com/rest/services-reference/enterprise/an-overview-of-routing-services.htm
- https://developers.arcgis.com/arcgis-rest-js/route-and-directions/
- https://developers.arcgis.com/arcgis-rest-js/route-and-directions/find-a-route-and-directions/

I hope this helps!
