### ISSUE TITLE
Start and Finish better terminology?

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri-leaflet-routing#8]
Start and Finish might be better terminology than Start and End.

var myRoute = new L.esri.Routing.Route({
    optimize: true,
}).start(latlng).finish(latlng).addTo(map);

**Comment by nixta** [comment]
We had a similar debate with the quickstart repos and I think we settled on "end":

https://github.com/Esri/quickstart-map-js/blob/master/html/directions/directions.html#L173-L174
and
https://github.com/Esri/quickstart-map-ios/blob/master/Lib/EsriQuickStartLib/GeoServices/EQSGeoServices.h#L28-L30

It may have been that talking about a route having a Start, Stops, and an End is clearer than it having a Start, Stops and a Finish.

**Comment by jgravois** [comment]
+1 for 'end'

**Comment by nixta** [comment]
I'm gonna throw this out there: What about From and To as in the iOS quickstart external parameter names?

https://github.com/Esri/quickstart-map-ios/blob/master/Lib/EsriQuickStartLib/GeoServices/EQSGeoServices.h#L28-L30

Taking that concept, _this_ reads very nicely to me:

`L.esri.Routing.Route().from().to().via()`

To handle optimized routes (see the routing properties `findBestSequence`, `preserveFirstStop` and `preserveLastStop` [here](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Route_service_with_synchronous_execution/02r300000036000000/), this could work something like `L.esri.Routing.Route()`:

| Syntax | Notes | findBestSequence | preserveFirstStop | preserveLastStop |
| --- | --- | --- | --- | --- |
| `.from().to()` | start + end | `false` | `true` | `true` |
| `.from().to().via()` | start + end + stops | `true` | `true` | `true` |
| `.from().via()` | start + stops | `true` | `true` | `false` |
| `.to().via()` | end + stops | `true` | `false` | `true` |
| `.via()` | stops | `true` | `false` | `false` |

So to get from A to B via C and D in best order you would `L.esri.Routing.Route().from(A).to(B).via(C,D)`.

However, how would you specify that you wanted to visit stops in order? Still thinking about that one.

**Comment by nixta** [comment]
What about:

``` JavaScript
var myRoute = new L.esri.Routing.Route({
    preserveOrder: true
}).from(A).to(B).via(C,D)
```

Where `A`,`B`,`C`,`D` can either be simple points or a `Stop` object?

**Comment by nixta** [comment]
Actually, I think the default should be to go in order since that's the cheaper option credits-wise. So instead:

| Syntax | Notes | findBestSequence | preserveFirstStop | preserveLastStop |
| --- | --- | --- | --- | --- |
| `.from().to()` | start + end | `false` | `N/A` | `N/A` |
| `.from().to().via()` | start + stops + end | `false` | `N/A` | `N/A` |
| `.from().via()` | start + stops | `false` | `N/A` | `N/A` |
| `.to().via()` | stops + end | `false` | `N/A` | `N/A` |
| `.via()` | stops | `false` | `N/A` | `N/A` |

And if they want optimized routes, they should specify a `findBestOrder` parameter with:

``` JavaScript
var myRoute = new L.esri.Routing.Route({
    findBestOrder: true
}).from(A).to(B).via(C,D,E,F,G)
```

In which case `findBestSequence` would be passed as `true`:

| Syntax | Notes | findBestSequence | preserveFirstStop | preserveLastStop |
| --- | --- | --- | --- | --- |
| `.from().to()` | start + end | `false` | `N/A` | `N/A` |
| `.from().to().via()` | start + stops + end | `true` | `true` | `true` |
| `.from().via()` | start + stops | `true` | `true` | `false` |
| `.to().via()` | stops + end | `true` | `false` | `true` |
| `.via()` | stops | `true` | `false` | `false` |

Note that `.from().to()` in this case is distinct from `.via()` with only two stops because, considering traffic etc. an optimized route might reverse the two stops.
